#server:
#port: 8082
#
#spring:
#datasource:
#url: jdbc:postgresql://localhost:5432/user_db
#username: postgres
#password: yourpassword
#
#jpa:
#hibernate:
#ddl-auto: update
#show-sql: true
#
#data:
#mongodb:
#uri: mongodb://localhost:27017/user_db
#
#redis:
#host: localhost
#port: 6379
#
#rabbitmq:
#host: localhost
#port: 5672
#username: guest
#password: guest
#
#logging:
#level:
#root: INFO
#com.oneandtwoshop: DEBUG