name: ci-cd
on:
  push: { branches: ["main"] }
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - name: Build & Test
        run: mvn -B -DskipTests=false clean verify

  docker-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push order-service
        run: |
          docker build -t ghcr.io/${{ github.repository }}/order-service:${{ github.sha }} order-service
          docker push ghcr.io/${{ github.repository }}/order-service:${{ github.sha }}
      - name: Build & Push product-service
        run: |
          docker build -t ghcr.io/${{ github.repository }}/product-service:${{ github.sha }} product-service
          docker push ghcr.io/${{ github.repository }}/product-service:${{ github.sha }}

  deploy:
    needs: docker-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
      - name: Set image tags and apply
        run: |
          sed -i "s|\${IMAGE_TAG}|${{ github.sha }}|g" k8s/order-deploy.yaml
          sed -i "s|\${IMAGE_TAG}|${{ github.sha }}|g" k8s/product-deploy.yaml
          kubectl apply -n oneandtwoshop -f k8s/namespace.yaml
          kubectl apply -n oneandtwoshop -f k8s/